// assets/Datepicker.vue
<template>
  <div class="field">
    <label class="label">Date</label>
    <div class="control">
      <input
        ref="dateInput"
        name="date"
        class="input"
        type="text"
        placeholder="When are you flying?">
    </div>
  </div>
</template>

<script>
import Pikaday from 'pikaday';
import 'moment';
import $ from 'jquery';

export default {
  data() {
    return { value: null };
  },
  mounted() {
    const pikaday = new Pikaday({
      field: $(this.$refs.dateInput)[0],
      onSelect: () => {
        this.value = pikaday.getMoment();
        this.$emit('select', this.value);
      },
    });
  },
};
</script>

// assets/Datepicker.jsx
import PropTypes from 'prop-types';
import React from 'react';
import Pikaday from 'pikaday';
import 'moment';

export default class Datepicker extends React.Component {
  constructor(props) {
    super(props);

    this.initPikaday = (field) => {
      const pikaday = new Pikaday({
        field,
        onSelect: () => {
          const { onSelect } = this.props;
          onSelect(pikaday.getMoment());
        },
      });
    };
  }

  render() {
    return (
      <div className="field">
        <div className="label">
          Date
        </div>
        <div className="control">
          <input
            name="date"
            className="input"
            type="text"
            placeholder="When are you flying?"
            ref={this.initPikaday}
          />
        </div>
      </div>
    );
  }
}

Datepicker.propTypes = {
  onSelect: PropTypes.func.isRequired,
};
