// assets/FlightSearchResults.jsx
import PropTypes from 'prop-types';
import React from 'react';

export default function FlightSearchResults({ flights }) {
  if (flights.state === 'completed') {
    return (
      <div className="section">
        <table className="table">
          <thead>
            <tr>
              <th>
                Airline
              </th>
              <th>
                Departure date
              </th>
              <th>
                Arrival date
              </th>
              <th />
            </tr>
          </thead>
          <tbody>
            {flights.data.map(flight => (
              <tr key={flight.key}>
                <td>
                  { flight.airline.name }
                </td>
                <td>
                  { flight.start.dateTime }
                </td>
                <td>
                  { flight.finish.dateTime }
                </td>
                <td>
                  <button type="button" className="button is-success">
                    { (flight.price).toLocaleString('en-US', { style: 'currency', currency: 'AUD' }) }
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

      </div>
    );
  }

  if (flights.state === 'pending') {
    return (
      <i className="fas fa-spinner fa-spin fa-3x" />
    );
  }

  if (flights.state === 'failed') {
    return (
      <div className="notification is-danger">
        { flights.error }

      </div>
    );
  }

  return (<div />);
}

FlightSearchResults.propTypes = {
  flights: PropTypes.shape({
    data: PropTypes.array,
    state: PropTypes.string,
    error: PropTypes.string,
  }).isRequired,
};

// assets/FlightSearchResults.vue
<template>
  <div class="section">
    <table
      v-if="flights.state === 'completed'"
      class="table">
      <thead>
        <tr>
          <th>Airline</th>
          <th>Departure date</th>
          <th>Arrival date</th>
          <th/>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="flight in flights.data"
          :key="flight.key">
          <td>
            {{ flight.airline.name }}
          </td>
          <td>
            {{ flight.start.dateTime }}
          </td>
          <td>
            {{ flight.finish.dateTime }}
          </td>
          <td>
            <a class="button is-success">
              {{ (flight.price).toLocaleString("en-US", {style: 'currency', currency: "AUD"}) }}
            </a>
          </td>
        </tr>
      </tbody>
    </table>

    <i
      v-if="flights.state === 'pending'"
      class="fas fa-spinner fa-spin fa-3x"/>

    <div
      v-if="flights.state === 'failed'"
      class="notification is-danger">{{ flights.error }}</div>

  </div>
</template>

<script>
export default {
  props: {
    flights: {
      type: Object,
      required: true,
    },
  },
};
</script>
